name: Test Interaction 
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
  push:
    branches: [ master ]

jobs:

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          1: Hello there
          This is the followup line
          2: How are you?
          3: I'm fine, thanks
        issue-copy: |
          1: 5, 6, 7, 8, 9, 10
          2: 1, 2, 3, 4, 5, 6
        pr-message: |
          1: Hello there
          2: How are you?
          3: I'm fine, thanks
        pr-copy: |
          1: 5, 6, 7, 8, 9, 10
          2: 11, 12, 13, 14, 15, 16