name: Test Interaction 
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
  push:
    branches: [ master ]

jobs:

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue: |
          1: Hello there
          2: How are you?
          3: I'm fine, thanks
        pull_request: |
          1: Hello there
          2: How are you?
          3: I'm fine, thanks
        copy:
         issue: |
            1: 5, 6, 7
         pull_request: |
            1: 5, 6, 7